# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        date
relative_permalinks: false

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /mdwiki-seed
author:
  name:           'Alexandre Dumas de Rauly'
  url:            https://twitter.com/dinobib

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: post
   values:
   layout: post