# Dependencies
pygments: true

# Permalinks
permalink: pretty

# Setup
title: Dino
tagline: The Jekyll Butler
url: http://dinobib.github.io/mdwiki-seed/
baseurl: /mdwiki-seed/
paginate: 1

author:
  name:           Alexandre Dumas de Rauly
  url:            https://twitter.com/dinobib
  email:          dinobib@gmail.com

# Custom vars
version:          1.0.0

auto: true
